name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/fastapi-starter
    permissions:
      id-token: write
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - uses: actions/checkout@v4
      - run: pipx install poetry
      - run: poetry install
      - run: poetry build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.8.14
