name: Status Checks

on: pull_request

jobs:
  code-style:
    uses: SituDevelopment/.github/.github/workflows/check-code-style.yaml@main
    with:
      python-root: fastapi_starter

  dependencies:
    uses: SituDevelopment/.github/.github/workflows/check-dependencies.yaml@main
